apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: demo
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - "manager"
      containers:
        - image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/demo-database:${BUILD_VERSION}
          imagePullPolicy: Always
          name: database
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: demo
  labels:
    app: database
spec:
  ports:
    - name: database-3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: database
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/demo-backend:${BUILD_VERSION}
          imagePullPolicy: Always
          name: backend
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  ports:
    - name: backend-8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
  namespace: demo
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/demo-frontend:${BUILD_VERSION}
          imagePullPolicy: Always
          name: frontend
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo
  labels:
    app: frontend
spec:
  ports:
    - name: frontend-443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: frontend
  type: ClusterIP
